name: Build and upload to qiniu CDN

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install packages
      run: npm i
    - name: Build Code
      run: npm run build:github
    - name: Deploy to CDN
      run: |
        dist=$GITHUB_WORKSPACE/dist
        prefix=d2-admin/preview/
        bucket=fairyever-site
        ./deploy/qshell account ${{ secrets.AK }} ${{ secrets.SK }} liyang
        ./deploy/qshell qupload2 --src-dir=$dist --bucket=$bucket --key-prefix=$prefix --overwrite=true --rescan-local=true
        ./deploy/qshell cdnrefresh --dirs -i ./deploy/cdnrefresh.txt