name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: test
      run: echo $GITHUB_WORKSPACE
    - name: test folder
      run: |
        cd $GITHUB_WORKSPACE
        ls
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install Yarn
      run: |
        curl -o- -L https://yarnpkg.com/install.sh | bash
        export PATH=$HOME/.yarn/bin:$PATH
    - name: Install packages
      run: yarn
    - name: Build Code
      run: yarn run build:github
    - name: Deploy to CDN
      run: |
        ./deploy/qshell account ${{ secrets.AK }} ${{ secrets.SK }} liyang
        ./deploy/qshell qupload2 --src-dir=$GITHUB_WORKSPACE/dist --bucket=fairyever-site --key-prefix=d2-admin/preview/ --ignore-dir=false --overwrite=true --check-exists=true --check-hash=true --check-size=true --rescan-local=true
        ./deploy/qshell cdnrefresh --dirs -i ./deploy/cdnrefresh.txt